"""Type stubs for geopy.distance package."""

from typing import Any, overload

class Distance:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def kilometers(self) -> float: ...
    @property
    def meters(self) -> float: ...
    @property
    def miles(self) -> float: ...
    @property
    def nautical(self) -> float: ...
    @property
    def ft(self) -> float: ...

@overload
def great_circle(
    point1: tuple[float, float], point2: tuple[float, float], **kwargs: Any
) -> Distance: ...
@overload
def great_circle(point1: Any, point2: Any, **kwargs: Any) -> Distance: ...
@overload
def geodesic(
    point1: tuple[float, float], point2: tuple[float, float], **kwargs: Any
) -> Distance: ...
@overload
def geodesic(point1: Any, point2: Any, **kwargs: Any) -> Distance: ...
