"""Type stubs for polyline package."""

from typing import List, Tuple, Union, overload

@overload
def decode(line: str) -> List[Tuple[float, float]]: ...
@overload
def decode(line: str, precision: int) -> List[Tuple[float, float]]: ...
@overload
def encode(coordinates: List[Tuple[float, float]]) -> str: ...
@overload
def encode(coordinates: List[Tuple[float, float]], precision: int) -> str: ...
