"""Type stubs for polyline package."""

from typing import overload

@overload
def decode(line: str) -> list[tuple[float, float]]: ...
@overload
def decode(line: str, precision: int) -> list[tuple[float, float]]: ...
@overload
def encode(coordinates: list[tuple[float, float]]) -> str: ...
@overload
def encode(coordinates: list[tuple[float, float]], precision: int) -> str: ...
